.de FN
\fI\|\\$1\|\fP
..
.TH "jabber-querybot" "1" "0.0.3"
.SH NAME
jabber-querybot \- a modular xmpp/jabber bot
.SH SYNOPSIS
jabber\-querybot
.PP
jabber\-querybot 2>&1 > /dev/null &
.SH DESCRIPTION
.PP
.FN jabber\-querybot
jabber-querybot connects a jabber account and wait for messages. If a message
comes in, it forward it to your self programmend modul. The return string of
your module, jabber-querybot send it back to the jabber sender.
.PP
It is designed to be re-usable and to make it easy to write small
Jabber bots that do one thing and do it well. A simple concept with a
lot of examples and experiences are implemented.
.PP
.B 1.
Create a jabber account on a jabber\-server around
.PP
.B 2.
Create a bot application:
.PP
 cd /usr/share/doc/jabber\-querybot/examples
 cp Testbot.pm /etc/jabber\-querybot/Mybot.pm
 cd /etc/jabber\-querybot
 ln \-s Mybot.pm Querymodule.pm
.PP
.B 3.
Modify login parameters to your jabber\-bot\-account
 vim Mybot.pm
  our $hostname	   = "swissjabber.ch";
  our $user            = "";
  our $password        = "";
  our $ident           = "Testbot";
  our $bot_admin       = "\@swissjabber.ch";
  our $port            = "5222";
  our $timeout         = "5";
  our $service_name    = "$user\@$hostname";
  our $bot_description = "Bot help title
  Bot description";
.PP
.B 4.
For each jabber message, jabber\-querybot will execute 
.B sub run_query,
that you can write here your application.
.PP
You can control how your jabber response will be:
.PP
.B error
= error message stanza
.PP
.B presence
= error as presence stanza
.PP
.B ignore
= ignore message
.SH OPTIONS
.FN jabber-querybot
has a lot of variables which you can easy modify for your needs:
.PP
.B $querystatus = [ 0 | 1 ]
.PP
 0 = Bot will not proceed any incoming jabber messages.
 1 = Bot will proceed incoming messages.
.PP
.B penalty_status
.PP
If the bot has too much workload, it goes to penalty status and wait some 
time until his status change back to normal.
.PP
.B $timer_reconnect_default = 21600
.PP
Every 21600 seconds (6 hours) the bot will shutdown automatically, wait 10 
seconds and starting up again. 
.PP
.B $timer_auto_query = 0
.PP
If you set in your module this variable to 60, the bot will every 60 seconds
call the function
.FN run_auto_query()
which you may use for several things.
.PP
.B System load
.PP
If your systems load is >=6, this bot will shutdown the jabber connection 
and check every 10 seconds systems load. If load <=2, bot will start over.
.PP
.SH EXAMPLES
.PP
Check example file:
 /usr/share/doc/jabber\-querybot/examples/Testbot.pm
.SH FILES
.FN /etc/jabber\-querybot/Querymodule.pm
 The main jabber\-querybot configuration file
.PP
.FN /usr/bin/jabber\-querybot
 Main perl program.
.SH AUTHORS
Written by Marco Balmer
.PP
.SH RESOURCES
.TP
http://github.com/micressor/jabber\-querybot/
