#!/bin/sh

set -e

# Can be removed, when 0.0.5-1 is migrated to stable.
if [ -L /etc/jabber-querybot/Querymodule.pm ] && \
   [ "$1" = "upgrade" ] && \
   [ "$2" = "0.0.4-1" ];
then
  if ls -l /etc/jabber-querybot/Querymodule.pm | grep -q \
    "/usr/share/doc/jabber-querybot/examples/Testbot.pm";
  then
    rm /etc/jabber-querybot/Querymodule.pm
  fi
fi

##DEBHELPER##
